language: node_js
node_js: "lts/*"
branches:
  only:
  - master
cache: yarn
install: yarn
script: yarn build
after_success: "find dist -type f -exec curl -v -u $SFTP_USER:$SFTP_PASSWORD --ftp-create-dirs -T {} $SFTP_URL{} \;"
